# Generated by Django 5.0.6 on 2024-08-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='CGSTPer',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='GstPer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='Invoice_date',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='Invoice_no',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='PurchaseCompany',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='SGSTPer',
            field=models.FloatField(null=True),
        ),
    ]
