# Generated by Django 5.0.6 on 2024-08-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0002_expenses_cgstper_expenses_gstper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Branch',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
