# Generated by Django 5.0.6 on 2024-08-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0003_account_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignee',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consignor',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
