# Generated by Django 5.0.6 on 2024-08-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0005_remove_addconsignment_receiver_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignment',
            name='weightAmt',
            field=models.FloatField(null=True),
        ),
    ]
