# Generated by Django 5.0.6 on 2024-08-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0006_alter_addconsignment_weightamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='godown',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignment',
            name='partdoor',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='godown',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='partdoor',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
