# Generated by Django 5.0.6 on 2024-08-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0007_addconsignment_godown_addconsignment_partdoor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addconsignment',
            old_name='partdoor',
            new_name='partydoor',
        ),
        migrations.RenameField(
            model_name='addconsignmenttemp',
            old_name='partdoor',
            new_name='partydoor',
        ),
    ]
