# Generated by Django 5.0.6 on 2024-08-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0010_remove_addconsignment_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='delivery',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='delivery',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
