# Generated by Django 5.0.6 on 2024-08-31 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0011_addconsignment_delivery_addconsignmenttemp_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='CGSTPer',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='GstPer',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Invoice_date',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Invoice_no',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='PurchaseCompany',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='SGSTPer',
        ),
    ]
