# Generated by Django 5.0.6 on 2024-09-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0016_expenses_staffname_staff_passbook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=50, null=True)),
                ('vehicalno', models.CharField(max_length=50, unique=True)),
                ('drivername', models.CharField(max_length=50, null=True)),
                ('ltrate', models.CharField(max_length=50, null=True)),
                ('liter', models.CharField(max_length=50, null=True)),
                ('total', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
