# Generated by Django 5.0.6 on 2024-09-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0017_disel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disel',
            name='liter',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disel',
            name='ltrate',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
