# Generated by Django 5.0.6 on 2024-09-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0019_alter_disel_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disel',
            name='liter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disel',
            name='ltrate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disel',
            name='total',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
