# Generated by Django 5.0.6 on 2024-09-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0021_alter_disel_liter_alter_disel_ltrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disel',
            name='vehicalno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
