# Generated by Django 5.0.6 on 2024-09-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0023_tripsheetprem_weightamt_tripsheettemp_weightamt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='track_number',
            field=models.CharField(max_length=50),
        ),
    ]
