# Generated by Django 5.0.6 on 2024-09-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0024_alter_account_track_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsheetprem',
            name='commission',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tripsheettemp',
            name='commission',
            field=models.IntegerField(null=True),
        ),
    ]
