# Generated by Django 5.0.6 on 2024-09-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0026_alter_tripsheetprem_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='date',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
