# Generated by Django 5.0.6 on 2024-09-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0027_alter_addconsignmenttemp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
