# Generated by Django 5.0.6 on 2024-09-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0034_disel_trip_id_alter_tripsheettemp_weightamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='agency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='services',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
