# Generated by Django 5.0.6 on 2024-09-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0035_branch_agency_branch_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='agency',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='services',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
