# Generated by Django 5.0.6 on 2024-09-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0036_alter_branch_agency_alter_branch_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='image',
        ),
        migrations.AddField(
            model_name='driver',
            name='aadhar',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
