# Generated by Django 5.0.6 on 2024-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0037_remove_branch_image_driver_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignment',
            name='Consignment_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='Consignment_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
