# Generated by Django 5.0.6 on 2024-09-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0038_alter_addconsignment_consignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignment',
            name='track_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='track_id',
            field=models.IntegerField(null=True),
        ),
    ]
