# Generated by Django 5.0.6 on 2024-09-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0040_alter_addconsignment_track_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addconsignment',
            name='Consignment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addconsignmenttemp',
            name='Consignment_id',
            field=models.IntegerField(null=True),
        ),
    ]
