# Generated by Django 5.0.6 on 2024-09-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0041_alter_addconsignment_consignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='emission',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='incurence',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permit',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rccard',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='aadhar',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
    ]
