# Generated by Django 5.0.6 on 2024-09-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0042_vehicle_emission_vehicle_incurence_vehicle_permit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='emissiondate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='incurencedate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permitdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rccardate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='taxdate',
            field=models.DateField(null=True),
        ),
    ]
